name: Publish to npm
on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Publish
        if: ${{ secrets.npm_token }}
        run: npm publish --provenance --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
