name: Create release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release. Will be passed to npm version, so you can use patch, minor and major as well.
        required: true
        default: patch

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install
        run: npm ci
      - name: Bump version
        run: |
          FOR /F "tokens=*" %%G IN ('npm version ${{ github.event.inputs.version }}') DO (
            SET NEW_VERSION=%%G
          )
          echo NEW_VERSION=%NEW_VERSION%>>%GITHUB_ENV%
      - name: echo
        run: echo The new version is %NEW_VERSION%
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
      - name: Build
        run: npm run build
