name: Test

on: pull_request

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm run build
      - run: npm ci
      - run: npm test
